### PR TITLE
Add sm_active and dhw_block Switches

### PR DESCRIPTION
**Pull request by PxPert**
Hi,
I've added two switches to your opentherm component:
- sm_active (Summer Mode)
- dhw_block (Domestic hot Water blocking

These switches are needed for some (for example mine :) ) boilers to correctly handle central heating and domestic hot water on/off functions.

Please note it's needed an updated version of Opentherm Library (See my other pull request at https://github.com/FreeBear-nc/opentherm_library/pull/1 )

PS I've updated the documentation too including the new switches

### CODE REVIEW

**Comment by FreeBear-nc** [comment]
Out of interest, make & model of your boiler ?
Would like to see what the manufacturer has to say about how the flags are handled if indeed that information is in the public domain.

**Comment by PxPert** [comment]
My boiler is a Riello Residence 30 KIS (Italian Gas boilers manufacturer).
Unfortunately I haven't found any documentation about their OpenTherm supported flags. The Summer mode and hot water lock functions were simply extracted from the opentherm table you've published in your opentherm-docs repository.
This is the only public documentation (it's an installation manual) I have found:
https://www.riello.it/catalogo/caldaie?action=download&id=20139527-eced9b8745aa650044dab5841d255535

The only reference about Opentherm (marked as OT+ in the manual) is the phisical layout of the pins, as you can see in Page 14

this boiler has Central heating and DHW functions (as you've probably imagined :) )

DHW is enabled if Summer mode is OFF OR DHW Function is ON
So I can deactivate it only by setting Summer Mode to ON AND DHW Function to OFF.

Central heating is instead enabled only if Summer mode is OFF AND Central Heating is ON

I've tried DHW Lock function but it doesn't seem to have effect. I only kept it for completeness, as it's documented in your table in the state Function

**Comment by FreeBear-nc** [comment]
> My boiler is a Riello Residence 30 KIS (Italian Gas boilers manufacturer). Unfortunately I haven't found any documentation about their OpenTherm supported flags. The Summer mode and hot water lock functions were simply extracted from the opentherm table you've published in your opentherm-docs repository. This is the only public documentation (it's an installation manual) I have found: https://www.riello.it/catalogo/caldaie?action=download&id=20139527-eced9b8745aa650044dab5841d255535

Found this too - https://www.riellokazan.hu/wp-content/uploads/2020/05/riello-residence-KIS-telepitesi-ca.pdf - Appears to be the English version of the installation manual.

Summer/Winter mode and DHW Blocking is briefly documented over on https://otgw.tclcode.com/firmware.html

>  SM=state
>     Set summer mode. Indicate to the boiler when summer condition is in effect. It depends on the boiler which effect this setting will have. When state is 1, summer mode is forced active. When state is 0, the thermostat controls the summer/winter mode. There is no option to force winter mode.
>     Examples: SM=1, SM=0 
> BW=state
>     DHW blocking. Switch off all DHW functions of the boiler. This can be used when some other equipment will provide DHW, like a solar boiler. When state is 1, DHW blocking is forced on. When state is 0, the thermostat controls DHW blocking. There is no option to force DHW blocking to off.
>

**Comment by PxPert** [comment]
Thanks, I'll take a look at the documentation you've provided.
Now I've almost all the feature I need. The only one remaining is remote boiler reset in case of error (In case it's supported by OpenTherm/Boiler), as my boiler sometimes locks due to exhaust error and needs to be manually reset ;)
PS If you'd like to take a look to my esphome configuration for my boiler (Attached to an ESP8266 with onboard LCD display and push button), you can find it here: https://github.com/PxPert/esphome/blob/master/caldaia.yaml


Thanks again for your work

**Comment by PxPert** [comment]
Have a look at the Boiler Lock-out Reset switch - That may be the answer to your problem. <- That should be exactly the switch I was looking for, now I only need to wait for the boiler to lock (fortunately it occours very rarely, about one time every 3 months) to test it.

For the Secrets: yes I know, but that only temporary until I finalize my yaml and then use the "final" password i use for all my devices that's in the secret yaml (and obviously not commited). My device is still in a work in progress state :)

**Pull request merged**
